// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import path from 'path';
import { defineConfig, env } from 'prisma/config';

// Load env files in order of priority (same as Next.js)
const envs = ['.env.production.local', '.env.development.local', '.env.local', '.env.production', '.env.development', '.env'];
envs.forEach((file) => {
  config({ path: path.resolve(process.cwd(), file) });
});

console.log("--- DEBUG PRISMA CONFIG ---");
console.log("process.cwd():", process.cwd());
console.log("DATABASE_URL length:", process.env.DATABASE_URL ? process.env.DATABASE_URL.length : "undefined");
console.log("DATABASE_URL value:", process.env.DATABASE_URL);
console.log("----------------------------");

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error("DATABASE_URL is not defined in environment files");
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: databaseUrl,
  },
});
